
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - scale.spectrum.ibm.com
  resources:
  - csis
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - scale.spectrum.ibm.com
  resources:
  - csis/finalizers
  verbs:
  - update
- apiGroups:
  - scale.spectrum.ibm.com
  resources:
  - csis/status
  verbs:
  - get
  - patch
  - update
